name: pytorch-CycleGAN-and-pix2pix
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.5.0
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-blosc2=2.12.0
  - ca-certificates=2025.2.25
  - certifi=2024.8.30
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - contourpy=1.0.5
  - cudatoolkit=10.2.89
  - cycler=0.11.0
  - dav1d=1.2.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - giflib=5.2.2
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - imagecodecs=2023.1.23
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.1.2
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.1.4
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libssh2=1.11.0
  - libtiff=4.5.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - msys2-conda-epoch=20160418
  - ninja=1.12.1
  - ninja-base=1.12.1
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - onnx=1.16.2
  - openjpeg=2.5.2
  - openssl=3.4.1
  - packaging=24.1
  - pandas=2.0.3
  - pillow=9.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.8
  - pytz=2024.1
  - qt-main=5.15.2
  - requests=2.32.3
  - scipy=1.10.1
  - setuptools=75.1.0
  - sip=6.7.12
  - snappy=1.1.10
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tomli=2.0.1
  - typing_extensions=4.11.0
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vs2015_runtime=14.42.34433
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.6.4
  - zfp=1.0.1
  - zipp=3.20.2
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - asgiref==3.8.1
      - backports-zoneinfo==0.2.1
      - click==8.1.8
      - colorama==0.4.6
      - django==4.2.21
      - docker-pycreds==0.4.0
      - dominate==2.4.0
      - eval-type-backport==0.2.2
      - filelock==3.16.1
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - imageio==2.35.1
      - jinja2==3.1.5
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.1
      - opencv-python==4.11.0.86
      - protobuf==5.29.3
      - psutil==7.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - python-graphviz==0.20.3
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - scikit-image==0.21.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - sqlparse==0.5.3
      - sympy==1.13.3
      - tifffile==2023.7.10
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchsummary==1.5.1
      - torchvision==0.19.1+cu118
      - torchviz==0.0.3
      - tornado==6.4.2
      - typing-extensions==4.12.2
      - visdom==0.2.4
      - wandb==0.19.7
      - websocket-client==1.8.0

